/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Medhatelo (https://sketchfab.com/Medhatelo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/astronaut-helmet-315605194a474c7b95cd2a9083985d22
title: Astronaut Helmet
*/
// Code uses the GLTFJSX command line tool to automatically generate most of the code.
// required props such as rotation and position are then added
// scene.gltf and the preload relative paths are also changed to correct values when moved from the public folder to src
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function AstronautHelmet({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/astronaut_helmet/scene.gltf"
  );
  return (
    <group ref={group} position={position} {...props} dispose={null}>
      <group rotation={rotation}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-0.18, 20.79, 0.06]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group
              name="Black-one"
              position={[0, -3.42, -1.92]}
              rotation={[-1.82, 0, 0]}
            >
              <group position={[0, -0.19, -0.15]}>
                <mesh
                  geometry={nodes["Black-one_Standard_14_0"].geometry}
                  material={materials.Standard_14}
                />
              </group>
            </group>
            <mesh
              geometry={nodes["Helmet-Body_Helmet-Body_0"].geometry}
              material={materials["Helmet-Body"]}
            />
            <mesh
              geometry={nodes["Helmet-Body_helmet_glass_0"].geometry}
              material={materials.helmet_glass}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/space_exhibition_assets/astronaut_helmet/scene.gltf");
