/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Natural History Museum Vienna (https://sketchfab.com/NHMWien)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/franz-viehbocks-sokol-space-suit-a2d679620a254660b12c7274de9bfc07
title: Franz Viehböck's Sokol Space Suit
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function FranzSpaceSuit({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/franz_viehbocks_sokol_space_suit/scene.gltf"
  );
  return (
    <group ref={group} position={position} {...props} dispose={null}>
      <group rotation={rotation} scale={1}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={nodes.Object_2.material}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={nodes.Object_3.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "/space_exhibition_assets/franz_viehbocks_sokol_space_suit/scene.gltf"
);
