/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lightwarrior (https://sketchfab.com/lightwarrior)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/victory-class-star-destroyer-b8cc09d62b154fc8bc26ca9bc1a456ae
title: Victory-Class Star Destroyer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function VictoryClass({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/victory-class_star_destroyer/scene.gltf"
  );
  return (
    <group ref={group} position={position} {...props} dispose={null}>
      <group rotation={rotation}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <group position={[0, 0, -9.56]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0009_Tex_0016_0dds_0.geometry}
              material={materials["Tex_0016_0.dds"]}
            />
          </group>
          <group position={[0, 0, -9.56]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0010_Tex_0020_0dds_0.geometry}
              material={materials["Tex_0020_0.dds"]}
            />
          </group>
          <group position={[0, 0, -9.56]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0011_Tex_0016_0dds_0.geometry}
              material={materials["Tex_0016_0.dds_0"]}
            />
          </group>
          <group position={[0, 0, -9.56]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0012_Tex_0024_0dds_0.geometry}
              material={materials["Tex_0024_0.dds"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
