/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Microsoft (https://sketchfab.com/microsoft)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/37f28664ac644b4f87a7bcfe0585ec20
title: Saturn V Rocket
*/

import React, { useRef } from "react";
import { useState } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function SaturnV({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/saturn_v_rocket/scene.gltf"
  );
  const [hover, setHover] = useState(false);

  useFrame(() => {
    group.current.rotation.y += 0.003;
  });

  return (
    <group
      position={position}
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={() => {
        setHover(true);
      }}
      onPointerOut={() => {
        setHover(false);
      }}
      scale={hover ? 1.05 : 1}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.saturnv.geometry}
          material={materials.Scene__Root}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/space_exhibition_assets/saturn_v_rocket/scene.gltf");
