/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MalteHedenstrom (https://sketchfab.com/MalteHedenstrom)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/space-helmet-study-367cec9498314678b0ab6cc93bbb82f6
title: Space Helmet Study
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function SpaceHelmet({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/space_helmet_study/scene.gltf"
  );
  return (
    <group ref={group} position={position} {...props} dispose={null}>
      <group rotation={rotation}>
        <group scale={10}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[1.99, 2.21, 1.57]} rotation={[2.06, 0.39, -0.89]}>
              <mesh
                geometry={nodes.pCylinder19_UV_Material_0.geometry}
                material={nodes.pCylinder19_UV_Material_0.material}
              />
            </group>
            <mesh
              geometry={nodes.pCylinder20_UV_Material_0.geometry}
              material={nodes.pCylinder20_UV_Material_0.material}
            />
            <group position={[1.98, 2.62, 1.59]} rotation={[2.06, 0.39, -0.89]}>
              <mesh
                geometry={nodes.pCylinder21_UV_Material_0.geometry}
                material={nodes.pCylinder21_UV_Material_0.material}
              />
            </group>
            <group position={[1.72, 3.28, 1.8]} rotation={[2.11, 0.6, -1]}>
              <mesh
                geometry={nodes.pCylinder22_UV_Material_0.geometry}
                material={nodes.pCylinder22_UV_Material_0.material}
              />
            </group>
            <group position={[1.85, 1.64, 1.72]} rotation={[2.07, 0.38, -0.93]}>
              <mesh
                geometry={nodes.pCylinder23_UV_Material_0.geometry}
                material={nodes.pCylinder23_UV_Material_0.material}
              />
            </group>
            <group
              position={[-2.46, 2.36, -0.36]}
              rotation={[0.94, 0.01, 1.54]}
            >
              <mesh
                geometry={nodes.pCylinder24_UV_Material_0.geometry}
                material={nodes.pCylinder24_UV_Material_0.material}
              />
            </group>
            <group
              position={[-2.57, 2.36, -0.09]}
              rotation={[0.94, 0.01, 1.54]}
            >
              <mesh
                geometry={nodes.pCylinder25_UV_Material_0.geometry}
                material={nodes.pCylinder25_UV_Material_0.material}
              />
            </group>
            <group position={[-2.44, 2.36, 1.22]} rotation={[0.94, 0.01, 1.54]}>
              <mesh
                geometry={nodes.pCylinder26_UV_Material_0.geometry}
                material={nodes.pCylinder26_UV_Material_0.material}
              />
            </group>
            <group position={[2.03, 0.69, 1.01]} rotation={[2.41, 0.29, -1.27]}>
              <mesh
                geometry={nodes.pCylinder30_UV_Material_0.geometry}
                material={nodes.pCylinder30_UV_Material_0.material}
              />
            </group>
            <group position={[2.2, 0.76, 0.54]} rotation={[2.48, 0.2, -1.39]}>
              <mesh
                geometry={nodes.pCylinder31_UV_Material_0.geometry}
                material={nodes.pCylinder31_UV_Material_0.material}
              />
            </group>
            <group
              position={[-2.24, 1.35, -0.13]}
              rotation={[0.93, -0.04, 1.55]}
              scale={[0.81, 0.81, 0.81]}
            >
              <mesh
                geometry={nodes.pCylinder33_UV_Material_0.geometry}
                material={nodes.pCylinder33_UV_Material_0.material}
              />
            </group>
            <group
              position={[-2.24, 1.32, 0.22]}
              rotation={[0.93, -0.04, 1.55]}
              scale={[0.81, 0.81, 0.81]}
            >
              <mesh
                geometry={nodes.pCylinder34_UV_Material_0.geometry}
                material={nodes.pCylinder34_UV_Material_0.material}
              />
            </group>
            <group position={[2.28, 1.2, -0.21]} rotation={[2.29, 0, -1.58]}>
              <mesh
                geometry={nodes.pCylinder35_UV_Material_0.geometry}
                material={nodes.pCylinder35_UV_Material_0.material}
              />
            </group>
            <group position={[2.28, 1.16, 0.07]} rotation={[2.29, 0, -1.58]}>
              <mesh
                geometry={nodes.pCylinder36_UV_Material_0.geometry}
                material={nodes.pCylinder36_UV_Material_0.material}
              />
            </group>
            <group position={[0.14, 1.5, -2.27]} rotation={[1.38, -0.71, 3.14]}>
              <mesh
                geometry={nodes.pCylinder37_UV_Material_0.geometry}
                material={nodes.pCylinder37_UV_Material_0.material}
              />
            </group>
            <group
              position={[-0.14, 1.5, -2.27]}
              rotation={[1.38, -0.71, 3.14]}
            >
              <mesh
                geometry={nodes.pCylinder38_UV_Material_0.geometry}
                material={nodes.pCylinder38_UV_Material_0.material}
              />
            </group>
            <group
              position={[2.4, 2.25, 0.26]}
              rotation={[-3.12, -0.94, -0.02]}
            >
              <mesh
                geometry={nodes.pCylinder39_UV_Material_0.geometry}
                material={nodes.pCylinder39_UV_Material_0.material}
              />
            </group>
            <group
              position={[2.4, 2.51, 0.26]}
              rotation={[-3.12, -0.94, -0.02]}
            >
              <mesh
                geometry={nodes.pCylinder40_UV_Material_0.geometry}
                material={nodes.pCylinder40_UV_Material_0.material}
              />
            </group>
            <group position={[2.4, 2.57, 0.26]} rotation={[0.02, -0.94, -0.02]}>
              <mesh
                geometry={nodes.pCylinder41_UV_Material_0.geometry}
                material={nodes.pCylinder41_UV_Material_0.material}
              />
            </group>
            <group position={[2.4, 2.31, 0.26]} rotation={[0.02, -0.94, -0.02]}>
              <mesh
                geometry={nodes.pCylinder42_UV_Material_0.geometry}
                material={nodes.pCylinder42_UV_Material_0.material}
              />
            </group>
            <group position={[-1.74, 3.8, 1.81]} rotation={[1.25, 0.27, 0.72]}>
              <mesh
                geometry={nodes.pCylinder43_UV_Material_0.geometry}
                material={nodes.pCylinder43_UV_Material_0.material}
              />
            </group>
            <group position={[-1.86, 3.62, 1.72]} rotation={[1.25, 0.27, 0.72]}>
              <mesh
                geometry={nodes.pCylinder44_UV_Material_0.geometry}
                material={nodes.pCylinder44_UV_Material_0.material}
              />
            </group>
            <group position={[-1.85, 2.14, 1.74]} rotation={[1.37, 0.34, 0.8]}>
              <mesh
                geometry={nodes.pCylinder45_UV_Material_0.geometry}
                material={nodes.pCylinder45_UV_Material_0.material}
              />
            </group>
            <group position={[-1.94, 2.34, 1.66]} rotation={[1.34, 0.27, 0.81]}>
              <mesh
                geometry={nodes.pCylinder46_UV_Material_0.geometry}
                material={nodes.pCylinder46_UV_Material_0.material}
              />
            </group>
            <group position={[2.44, 2.41, -0.65]} rotation={[2.2, -0.01, -1.6]}>
              <mesh
                geometry={nodes.pCylinder32_UV_Material_0.geometry}
                material={nodes.pCylinder32_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5001_UV_Material_0.geometry}
                material={nodes.polySurface5001_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5002_UV_Material_0.geometry}
                material={nodes.polySurface5002_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5003_UV_Material_0.geometry}
                material={nodes.polySurface5003_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5004_UV_Material_0.geometry}
                material={nodes.polySurface5004_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5005_UV_Material_0.geometry}
                material={nodes.polySurface5005_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5006_UV_Material_0.geometry}
                material={nodes.polySurface5006_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5007_UV_Material_0.geometry}
                material={nodes.polySurface5007_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5008_UV_Material_0.geometry}
                material={nodes.polySurface5008_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5009_UV_Material_0.geometry}
                material={nodes.polySurface5009_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5010_UV_Material_0.geometry}
                material={nodes.polySurface5010_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5011_UV_Material_0.geometry}
                material={nodes.polySurface5011_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5012_UV_Material_0.geometry}
                material={nodes.polySurface5012_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5013_UV_Material_0.geometry}
                material={nodes.polySurface5013_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5014_UV_Material_0.geometry}
                material={nodes.polySurface5014_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5015_UV_Material_0.geometry}
                material={nodes.polySurface5015_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5016_UV_Material_0.geometry}
                material={nodes.polySurface5016_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5017_UV_Material_0.geometry}
                material={nodes.polySurface5017_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5018_UV_Material_0.geometry}
                material={nodes.polySurface5018_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5019_UV_Material_0.geometry}
                material={nodes.polySurface5019_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5020_UV_Material_0.geometry}
                material={nodes.polySurface5020_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5021_UV_Material_0.geometry}
                material={nodes.polySurface5021_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5022_UV_Material_0.geometry}
                material={nodes.polySurface5022_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5023_UV_Material_0.geometry}
                material={nodes.polySurface5023_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5024_UV_Material_0.geometry}
                material={nodes.polySurface5024_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5025_UV_Material_0.geometry}
                material={nodes.polySurface5025_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5026_UV_Material_0.geometry}
                material={nodes.polySurface5026_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5027_UV_Material_0.geometry}
                material={nodes.polySurface5027_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5028_UV_Material_0.geometry}
                material={nodes.polySurface5028_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5029_UV_Material_0.geometry}
                material={nodes.polySurface5029_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5030_UV_Material_0.geometry}
                material={nodes.polySurface5030_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5031_UV_Material_0.geometry}
                material={nodes.polySurface5031_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5032_UV_Material_0.geometry}
                material={nodes.polySurface5032_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5033_UV_Material_0.geometry}
                material={nodes.polySurface5033_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5034_UV_Material_0.geometry}
                material={nodes.polySurface5034_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5035_UV_Material_0.geometry}
                material={nodes.polySurface5035_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5036_UV_Material_0.geometry}
                material={nodes.polySurface5036_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5037_UV_Material_0.geometry}
                material={nodes.polySurface5037_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5038_UV_Material_0.geometry}
                material={nodes.polySurface5038_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5039_UV_Material_0.geometry}
                material={nodes.polySurface5039_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5040_UV_Material_0.geometry}
                material={nodes.polySurface5040_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5041_UV_Material_0.geometry}
                material={nodes.polySurface5041_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5042_UV_Material_0.geometry}
                material={nodes.polySurface5042_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5043_UV_Material_0.geometry}
                material={nodes.polySurface5043_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5044_UV_Material_0.geometry}
                material={nodes.polySurface5044_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5045_UV_Material_0.geometry}
                material={nodes.polySurface5045_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5046_UV_Material_0.geometry}
                material={nodes.polySurface5046_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5047_UV_Material_0.geometry}
                material={nodes.polySurface5047_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5048_UV_Material_0.geometry}
                material={nodes.polySurface5048_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5049_UV_Material_0.geometry}
                material={nodes.polySurface5049_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5050_UV_Material_0.geometry}
                material={nodes.polySurface5050_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5051_UV_Material_0.geometry}
                material={nodes.polySurface5051_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5052_UV_Material_0.geometry}
                material={nodes.polySurface5052_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5053_UV_Material_0.geometry}
                material={nodes.polySurface5053_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5054_UV_Material_0.geometry}
                material={nodes.polySurface5054_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5055_UV_Material_0.geometry}
                material={nodes.polySurface5055_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5056_UV_Material_0.geometry}
                material={nodes.polySurface5056_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5057_UV_Material_0.geometry}
                material={nodes.polySurface5057_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5058_UV_Material_0.geometry}
                material={nodes.polySurface5058_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5059_UV_Material_0.geometry}
                material={nodes.polySurface5059_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5060_UV_Material_0.geometry}
                material={nodes.polySurface5060_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5061_UV_Material_0.geometry}
                material={nodes.polySurface5061_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5062_UV_Material_0.geometry}
                material={nodes.polySurface5062_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5063_UV_Material_0.geometry}
                material={nodes.polySurface5063_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5064_UV_Material_0.geometry}
                material={nodes.polySurface5064_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5065_UV_Material_0.geometry}
                material={nodes.polySurface5065_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5066_UV_Material_0.geometry}
                material={nodes.polySurface5066_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5067_UV_Material_0.geometry}
                material={nodes.polySurface5067_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5068_UV_Material_0.geometry}
                material={nodes.polySurface5068_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5069_UV_Material_0.geometry}
                material={nodes.polySurface5069_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5070_UV_Material_0.geometry}
                material={nodes.polySurface5070_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5071_UV_Material_0.geometry}
                material={nodes.polySurface5071_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5072_UV_Material_0.geometry}
                material={nodes.polySurface5072_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5073_UV_Material_0.geometry}
                material={nodes.polySurface5073_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5074_UV_Material_0.geometry}
                material={nodes.polySurface5074_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5075_UV_Material_0.geometry}
                material={nodes.polySurface5075_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5076_UV_Material_0.geometry}
                material={nodes.polySurface5076_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5077_UV_Material_0.geometry}
                material={nodes.polySurface5077_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5078_UV_Material_0.geometry}
                material={nodes.polySurface5078_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5079_UV_Material_0.geometry}
                material={nodes.polySurface5079_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5080_UV_Material_0.geometry}
                material={nodes.polySurface5080_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5081_UV_Material_0.geometry}
                material={nodes.polySurface5081_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5082_UV_Material_0.geometry}
                material={nodes.polySurface5082_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5083_UV_Material_0.geometry}
                material={nodes.polySurface5083_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5084_UV_Material_0.geometry}
                material={nodes.polySurface5084_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5085_UV_Material_0.geometry}
                material={nodes.polySurface5085_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5086_UV_Material_0.geometry}
                material={nodes.polySurface5086_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5087_UV_Material_0.geometry}
                material={nodes.polySurface5087_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5088_UV_Material_0.geometry}
                material={nodes.polySurface5088_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5089_UV_Material_0.geometry}
                material={nodes.polySurface5089_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5090_UV_Material_0.geometry}
                material={nodes.polySurface5090_UV_Material_0.material}
              />
            </group>
            <group position={[0.02, 1.69, 0]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.polySurface5091_UV_Material_0.geometry}
                material={nodes.polySurface5091_UV_Material_0.material}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/space_exhibition_assets/space_helmet_study/scene.gltf");
