/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Wholock (https://sketchfab.com/wholock)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/star-trek-dderidex-class-warbird-4cd1e185eaa645b2ad3eeae31d0c5d0d
title: Star Trek - D'Deridex Class Warbird
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Dderidex({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/star_trek-dderidex/scene.gltf"
  );
  return (
    <group ref={group} position={position} {...props} dispose={null}>
      <group rotation={rotation}>
        <group rotation={[0, 0, -Math.PI]} scale={0.23}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={
                nodes.DDeridex_Class_Warbird_Dderidex_diffuse_1K_0.geometry
              }
              material={materials.Dderidex_diffuse_1K}
            />
            <mesh
              geometry={
                nodes.DDeridex_Class_Warbird_Dderidex_windows_1_0.geometry
              }
              material={materials.Dderidex_windows_1}
            />
            <group position={[-200, 200, 200]} rotation={[1.11, -0.42, 0.69]}>
              <group rotation={[Math.PI / 2, 0, 0]} />
            </group>
            <group position={[0, 0, 1467.77]} rotation={[0, Math.PI / 2, 0]} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/space_exhibition_assets/star_trek-dderidex/scene.gltf");
