/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lightwarrior (https://sketchfab.com/lightwarrior)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/resurgent-class-star-destroyer-4e226c776d534465ba1ceb307b68d34b
title: Resurgent-Class Star Destroyer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ResurgentClass({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/resurgent-class_star_destroyer/scene.gltf"
  );
  return (
    <group ref={group} position={position} {...props} dispose={null}>
      <group rotation={rotation}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0009_Tex_0015_0dds_0.geometry}
              material={materials["Tex_0015_0.dds"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0010_Tex_0020_0dds_0.geometry}
              material={materials["Tex_0020_0.dds"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0011_Tex_0020_0dds_0.geometry}
              material={materials["Tex_0020_0.dds_0"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0012_Tex_0020_0dds_0.geometry}
              material={materials["Tex_0020_0.dds_1"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0013_Tex_0024_0dds_0.geometry}
              material={materials["Tex_0024_0.dds"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0014_Tex_0026_0dds_0.geometry}
              material={materials["Tex_0026_0.dds"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  "/space_exhibition_assets/resurgent-class_star_destroyer/scene.gltf"
);
