/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lightwarrior (https://sketchfab.com/lightwarrior)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/venator-class-star-destroyer-235b5a20b5ab47c0845e7a40db3b6c51
title: Venator-Class Star Destroyer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function VenatorClass({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/venator-class_star_destroyer/scene.gltf"
  );
  return (
    <group ref={group} position={position} {...props} dispose={null}>
      <group rotation={rotation}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <group position={[0, 5.53, -2.93]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0010_Tex_0016_0dds_0.geometry}
              material={materials["Tex_0016_0.dds"]}
            />
          </group>
          <group position={[0, 5.53, -2.93]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Mesh_0019_Tex_0024_0dds_0.geometry}
              material={materials["Tex_0024_0.dds"]}
            />
          </group>
          <group
            position={[-0.28, -0.14, -55.71]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.77}
          >
            <group position={[0.28, -66.46, 6.91]}>
              <mesh
                geometry={nodes.Mesh_0020_Tex_0028_0dds_0.geometry}
                material={materials["Tex_0028_0.dds"]}
              />
            </group>
          </group>
          <group
            position={[-0.28, 0.3, -65.37]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.77}
          >
            <group position={[0.28, -79, 6.34]}>
              <mesh
                geometry={nodes.Mesh_0021_Tex_0032_0dds_0.geometry}
                material={materials["Tex_0032_0.dds"]}
              />
            </group>
          </group>
          <group
            position={[0.06, 5.9, -3.05]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.2}
          >
            <mesh
              geometry={nodes.Mesh_0026_Tex_0043_0dds_0.geometry}
              material={materials["Tex_0043_0.dds"]}
            />
          </group>
          <group
            position={[0.06, 5.9, -3.05]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.2}
          >
            <mesh
              geometry={nodes.Mesh_0027_Tex_0040_0dds_0.geometry}
              material={materials["Tex_0040_0.dds"]}
            />
          </group>
          <group
            position={[0.06, 5.9, -3.05]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.2}
          >
            <mesh
              geometry={nodes.Mesh_0028_Tex_0048_0dds_0.geometry}
              material={materials["Tex_0048_0.dds"]}
            />
          </group>
          <group
            position={[0.06, 5.9, -3.05]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.2}
          >
            <mesh
              geometry={nodes.Mesh_0025_Tex_0040_0dds_0.geometry}
              material={materials["Tex_0040_0.dds_0"]}
            />
          </group>
          <group
            position={[-0.23, 16.1, -31.6]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.37}
          >
            <group position={[0.62, -80.49, -30.61]}>
              <mesh
                geometry={nodes.Mesh_0022_Tex_0033_0dds_0.geometry}
                material={nodes.Mesh_0022_Tex_0033_0dds_0.material}
              />
            </group>
          </group>
          <group
            position={[3.08, 29.72, -22.09]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.36}
          >
            <group position={[-8.63, -54.46, -68.99]}>
              <mesh
                geometry={nodes.Object001_Tex_0033_0dds_0.geometry}
                material={nodes.Object001_Tex_0033_0dds_0.material}
              />
            </group>
          </group>
          <group
            position={[-3.48, 29.72, -22.09]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.36}
          >
            <group position={[9.87, -54.46, -68.99]}>
              <mesh
                geometry={nodes.Object002_Tex_0033_0dds_0.geometry}
                material={nodes.Object002_Tex_0033_0dds_0.material}
              />
            </group>
          </group>
          <group
            position={[5.16, 29.72, -22.36]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.36}
          >
            <group position={[-14.53, -55.21, -68.97]}>
              <mesh
                geometry={nodes.Object003_Tex_0033_0dds_0.geometry}
                material={nodes.Object003_Tex_0033_0dds_0.material}
              />
            </group>
          </group>
          <group
            position={[-0.23, 17.04, -24.57]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.36}
          >
            <group position={[0.62, -61.25, -32.86]}>
              <mesh
                geometry={nodes.Object004_Tex_0033_0dds_0.geometry}
                material={nodes.Object004_Tex_0033_0dds_0.material}
              />
            </group>
          </group>
          <group
            position={[-0.23, 14.61, -15.42]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.36}
          >
            <group position={[0.62, -35.38, -25.89]}>
              <mesh
                geometry={nodes.Object005_Tex_0033_0dds_0.geometry}
                material={nodes.Object005_Tex_0033_0dds_0.material}
              />
            </group>
          </group>
          <group
            position={[7.96, 13.13, -32.92]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.41}
          >
            <group position={[-22.83, -85.64, -21.58]}>
              <mesh
                geometry={nodes.Object006_Tex_0033_0dds_0.geometry}
                material={nodes.Object006_Tex_0033_0dds_0.material}
              />
            </group>
          </group>
          <group
            position={[-8.45, 13.14, -32.93]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.41}
          >
            <group position={[24.07, -85.64, -21.58]}>
              <mesh
                geometry={nodes.Object007_Tex_0033_0dds_0.geometry}
                material={nodes.Object007_Tex_0033_0dds_0.material}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  "/space_exhibition_assets/venator-class_star_destroyer/scene.gltf"
);
