/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Wholock (https://sketchfab.com/wholock)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/star-trek-dsc-enterprise-98cdebaa7fae4752bcaa5a35453d224c
title: Star Trek - DSC Enterprise
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Enterprise({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/star_trek-enterprise/scene.gltf"
  );
  return (
    <group ref={group} position={position} {...props} dispose={null}>
      <group rotation={rotation}>
        <group position={[0, 14.4, 0]} rotation={[0, 0, -Math.PI]} scale={5}>
          <mesh
            geometry={nodes.mesh_0.geometry}
            material={materials.material_0}
          />
          <mesh
            geometry={nodes.mesh_1.geometry}
            material={materials.material_1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/space_exhibition_assets/star_trek-enterprise/scene.gltf");
