/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Microsoft (https://sketchfab.com/microsoft)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/b82e419607214780a5c65e4a8f455735
title: Booster Rockets and Fuel Tank
*/

import React, { useRef } from "react";
import { useState } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

import { Modal } from "react-responsive-modal";

export default function BoosterRocket({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/booster_rockets_and_fuel_tank/scene.gltf"
  );
  const [hover, setHover] = useState(false);

  useFrame(() => {
    group.current.rotation.y += 0.001;
  });

  // const [open, setOpen] = useState(false);

  // const onOpenModal = () => setOpen(true);
  // const onCloseModal = () => setOpen(false);

  return (
    <>
      <group
        position={position}
        ref={group}
        {...props}
        dispose={null}
        onPointerOver={() => {
          setHover(true);
        }}
        onPointerOut={() => {
          setHover(false);
        }}
        scale={hover ? 1.05 : 1}
        // onClick={() => {
        //   setOpen(true);
        // }}
      >
        <group rotation={rotation}>
          <mesh
            geometry={nodes.booster.geometry}
            material={materials.Material__198}
          />
        </group>
      </group>
      {/* <Modal
        open={open}
        onClose={() => {
          setOpen(false);
        }}
        center
      >
        <h2>Simple centered modal</h2>
      </Modal> */}
    </>
  );
}

useGLTF.preload(
  "/space_exhibition_assets/booster_rockets_and_fuel_tank/scene.gltf"
);
