/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Microsoft (https://sketchfab.com/microsoft)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/ff4b00b7ebb24fdd98fb96b08f2c43c9
title: Space Shuttle
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ShuttleModel({ position, rotation, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/space_exhibition_assets/space_shuttle/scene.gltf"
  );
  return (
    <group position={position} ref={group} {...props} dispose={null}>
      <group rotation={rotation}>
        <mesh
          geometry={nodes.shuttle.geometry}
          material={materials.Material__197}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/space_exhibition_assets/space_shuttle/scene.gltf");
